### ISSUE TITLE
ServerHardware #GetServerHardwareList Issues

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-golang#103]
In [ServerHardware #GetServerHardwareList](https://github.com/HewlettPackard/oneview-golang/blob/master/ov/server_hardware.go#L225), I think there are a few issues:

1. The REST [here](https://github.com/HewlettPackard/oneview-golang/blob/master/ov/server_hardware.go#L247) call doesn't handle errors
2. [This section](https://github.com/HewlettPackard/oneview-golang/blob/master/ov/server_hardware.go#L249) doesn't appear to do anything useful (does it?). Maybe it was left in after a refactor?
3. Unmarshalling the data doesn't set the Client property, so many subsequent calls on the objects returned (e.g. `PowerOff()`) will fail unless you set the Client property manually.

**Comment by supreethpy** [comment]
#115

**Comment by VenkateshRavula** [comment]
The fix for this issue is provided in https://github.com/HewlettPackard/oneview-golang/pull/137.
Closing this issue now. Feel free to reopen if the issue still exists.
