### ISSUE TITLE
Server Profile Template support for API 500+

### ISSUE THREAD

**Issue by adarobin** [HewlettPackard/oneview-golang#119]
API version 500 and up have a new field named `connectionSettings` that now contains the `connections` field used on the Server Profiles deployed from the template.

**Comment by soodpr** [comment]
@adarobin - we are adding support for API800 for server profile and server profile template. 
I think this issue will be handled in that. Please find the [PR](https://github.com/HewlettPackard/oneview-golang/pull/140/) for the same.

**Comment by adarobin** [comment]
@soodpr Great!  I'll take a crack at getting it to work in Terraform once this is merged unless that is already on your roadmap.

**Comment by soodpr** [comment]
@adarobin - Thanks for your contributions to both OneView-Go and OneView Terraform. We do have a roadmap for OneView API800 support for Terraform. But would like to get your inputs first. We would like to touch base with you if possible.

**Comment by jyothis-gireesan** [comment]
Added the field in PR for Server Profile and Server Profile Template 
https://github.com/HewlettPackard/oneview-golang/pull/140

**Comment by adarobin** [comment]
@soodpr Sounds good.  Feel free to shoot me an e-mail and we can set something up.

**Comment by soodpr** [comment]
@adarobin - sure. can you please share your emailId.

**Comment by adarobin** [comment]
@soodpr adarobin@umich.edu
