### ISSUE TITLE
Fix Docker Setup section in README.md

### ISSUE THREAD

**Issue by padlia** [HewlettPackard/oneview-golang#285]
### Scenario/Intent
Reading up the documentation to install docker container

### Environment Details
 - **Golang binding for HPE OneView Version:** [Version of this module for which you are encountering the issue]
 - **OneView SDK Version:** [Version of the Oneview SDK for which you are encountering the issue]
 - **OneView Appliance Version:** [Version of the OneView appliance you're interacting with]
 - **OneView Client API Version:** [API version of your client object]
 - **Golang Version:** [Version of Golang in your environment]
 - **Platform:** [OS distribution and release version]

-Not Applicable-

### Steps to Reproduce
[What are the complete steps needed to do in order to reproduce your problem?]

Read https://github.com/HewlettPackard/oneview-golang/blob/master/README.md#docker-setup

### Expected Result
[What do you *expect* to happen after taking the steps above?]

Expect the section to refer golang SDK and not Ruby SDK

### Actual Result
[What *actually* happens after the steps above? Include error output or a link to a gist.]

From https://github.com/HewlettPackard/oneview-golang/blob/master/README.md#docker-setup

The light weight containerized version of the HPE OneView SDK for **Ruby** is available in the Docker Store. The Docker Store image tag consist of two sections: <sdk_version-OV_version>

1. In the above statement, Ruby should be replaced with golang.
2. In the above statement, the URL to Docker Store should point to golang container, and not the Ruby container.

**Comment by AsisBagga** [comment]
@padlia Hi Padlia, Thanks for pointing this out. Will take care of this issue in our coming release.

**Comment by padlia** [comment]
OK, thx @AsisBagga

**Comment by AsisBagga** [comment]
The Changes are updated in the source code, good to close the issue.
