### ISSUE TITLE
GetServerHardwareList only returns 32 Servers or panics

### ISSUE THREAD

**Issue by stephan-koch** [HewlettPackard/oneview-golang#301]
### Scenario/Intent
ovc.GetServerHardwareList(filters, "", "", "", "") only returns 32 Servers

### Environment Details
 - **Golang binding for HPE OneView Version:** 1.80

### Steps to Reproduce
Use the serverhardware.go example from the repo against an appliance with more then 32 servers

### Expected Result
getting all servers like it will be done with Powershell or Python.
curl itself also does only get the first 32 entries.
Please refer to count value and nextpageURI
HPE internally discussed here: https://web.yammer.com/main/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMTExMjk1NTY5NjYxOTUyMCJ9

### Actual Result

panic: runtime error: index out of range [32] with length 32

goroutine 1 [running]:
github.com/HewlettPackard/oneview-golang/ov.(*OVClient).GetServerHardwareList(0xc0000cc000, 0xc0000134c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/skoch/go/src/github.com/HewlettPackard/oneview-golang/ov/server_hardware.go:302 +0xac5
main.main()
        /home/skoch/serverhw.go:25 +0x23b
exit status 2

**Comment by AsisBagga** [comment]
@stephan-koch Hi Stephen, technically it should return limeted number of queryset. If you try to set query parameter count then API request the required number of queryset. A count of -1 requests all the items as below:
```
// This should be in your case which is to get all servers
ovc.GetServerHardwareList(filters, "", "", "-1", "") 
```

Example:
Return the first 100 items in a list of resources:
start=0&count=100
```
filters := []string{""}
ovc.GetServerHardwareList(filters, "", "0", "100", "")
```
This parameter only applies to GET (read) requests that return a list of resources. Use start and count to retrieve a large set of resources in smaller groups.

Meanwhile I'll check in lab for same.

**Comment by stephan-koch** [comment]
wit this option i am getting the panic also

....
serverList : CTC H5 HE01, bay 9
serverList : CTC H5 HE11, bay 5
panic: runtime error: index out of range [32] with length 32

goroutine 1 [running]:
github.com/HewlettPackard/oneview-golang/ov.(*OVClient).GetServerHardwareList(0xc0000ca000, 0xc0001382d0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x71e1b1, 0x2, ...)
        /home/skoch/go/src/github.com/HewlettPackard/oneview-golang/ov/server_hardware.go:302 +0xac5
main.main()
        /home/skoch/serverhw.go:25 +0x24b
exit status 2

**Comment by AsisBagga** [comment]
Thanks @stephan-koch for raising this bug, Shanmugam is looking into this bug and will update soon.

**Comment by SHANDCRUZ** [comment]
Hi @stephan-koch,  The issue has been resolved from our end and repository has been updated. I will proceed with closing this issue. If you have any further concern please feel free to reopen or open new issue.
