### ISSUE TITLE
GetStorageVolumes() Unmarshal Error

### ISSUE THREAD

**Issue by osanchez42** [HewlettPackard/oneview-golang#368]
Scenario/Intent
I am trying to call function GetStorageVolumes("", "") to get the StorageVolumesList

Environment Details
Golang binding for HPE OneView Version: v7.1.0
OneView SDK Version: 700
OneView Appliance Version: 6.50.00-0452161
OneView Client API Version: 3600
Golang Version: 1.18.2
Platform: Centos 7

Steps to Reproduce

```
func getStorageVolumes(client *ov.OVClient) (ov.StorageVolumesList, error) {
	storageVolumesList, err := client.GetStorageVolumes("", "")
	if err != nil {
		return ov.StorageVolumesList{}, err
	}
	return storageVolumesList, err
}
```

Expected Result
Storage Volumes list is returned as expected

Actual Result
`json: cannot unmarshal string into Go struct field DeviceSpecificAttributes.members.deviceSpecificAttributes.id of type int`

**Comment by nabhajit-ray** [comment]
Hi,

We will look into this and get back to you

**Comment by alisha-k-kalladassery** [comment]
Hi,
This issue is fixed and changes are available in master branch. The same will be available in OV7.2 release.
