### ISSUE TITLE
3.0 OneView compatability

### ISSUE THREAD

**Issue by wenlock** [HewlettPackard/oneview-golang#38]
When doing a new deploy on 30 API we get this error:

REQ    --> &{Method:POST URL:https://10.0.10.118/rest/server-profiles?filter=serverHardwareTypeUri%3D%27%2Frest%2Fserver-hardware-types%2FD086A170-DF72-4D4C-BFE8-40B2BAEA1A2E%27&filter=serverGroupUri%3D%27%2Frest%2Fenclosure-groups%2F70536257-794b-4349-917a-59e5ddc60d39%27&sort=name%3Aasc Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Auth:[LTE5MDc1ODE3MzI0jsJqmR7sWGgggEJxmX3ZaR_7A1FHCzKz] Content-Type:[application/json; charset=utf-8] X-Api-Version:[300]] Body:{Reader:} ContentLength:1719 TransferEncoding:[] Close:false Host:10.0.10.118 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil>}

RESP   --> &{Status:400 Bad Request StatusCode:400 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Via:[1.1 example.com] Cache-Control:[no-cache] Date:[Thu, 19 Nov 2015 17:58:41 GMT] Server:[Apache] Content-Type:[application/json;charset=UTF-8]] Body:0x129bbd40 ContentLength:-1 TransferEncoding:[chunked] Close:true Trailer:map[] Request:0x12974700 TLS:0x12a9a7c0}

ERROR  --> <nil>

Error submitting new profile request: Error in response: The field named StorageTargetType near line 1, column 1,697 is not a valid field in this JSON object.
 Response Status: 400 Bad Request

**Comment by nabhajit-ray** [comment]
Closing it as per the previous comment . Let us know if it is still reproducible
