### ISSUE TITLE
Can't use a fully qualified filename to load config 

### ISSUE THREAD

**Issue by pyfontan** [HewlettPackard/oneview-golang#422]
### Scenario/Intent
Load a config from a file which is not in the same path that the CLI using oneview-golang.

### Environment Details
 - **OneView SDK Version:** v9.1.0
 - **OneView Appliance Version:**  9.00.00-0493574 
 - **Golang Version:** v1.22.1
 - **Platform:** Ubuntu 24.04

### Steps to Reproduce
Use LoadConfigFile function with a value of configFile parameter equal to `/etc/whatever.json` 

### Expected Result
Configuration object loaded from file `/etc/whatever.json`

### Actual Result
Open file error because de LoadConfigFile function prepends the configFile with the path of Caller.

**Comment by alisha-k-kalladassery** [comment]
Hi @pyfontan 

We went through your PR and understood the issue you are facing. But your PR doesn't seem to solve the issue as we tried running it. 
Please let us know if you need any further help on this.

Thanks,
Alisha

**Comment by pyfontan** [comment]
Hi @alisha-k-kalladassery 

I created the new [LoadConfigFilePath](https://github.com/pyfontan/oneview-golang/blob/feature/config_from_slash/ov/config.go#L96)  in order to be able to load a config file with a full path.

I didn't want to break the operation of the initial function LoadConfigFile

Hope it helps.
Thanks
Pierre-yves

**Comment by alisha-k-kalladassery** [comment]
Thanks @pyfontan .
We checked it and it is working fine. We will approve it and if workflows run fine, We can merge the same.

Thanks
Alisha
