### ISSUE TITLE
Receiving: Error! No available blades that are compatible with the server profile!

### ISSUE THREAD

**Issue by LukasRe** [HewlettPackard/oneview-golang#90]
Hi,

I wanted to deploy Docker on an DL 380 Gen9 but I receive the error:

DBG | Error with getting available hardware: Error! No available blades that are compatible with the server profile!

Any ideas?

BR LR

**Comment by AsisBagga** [comment]
@LukasRe Hi Lukas, 
Did you tried creating Server Profile on OneView to check if there you're getting similar error there or not? 
To reproduce the issue from my end, I would need a detail information. 
Can you share your playbook and few more information ,for example, what is the SDK version and OV version you're using?

**Comment by AsisBagga** [comment]
@LukasRe Hi Lukas,
Since we haven't received any response yet, i will have to close this issue. You may open a new issue referring to this issue, we would be glad to assist you. Thank you.
